### ISSUE TITLE
unable to execute DELETE queries

### ISSUE THREAD

**Issue by sescobb27** [HGInsights/snowpack#41]
**Describe the bug**
Hey there, i'm trying to test your library which looks pretty good, but got some errors trying to delete data, which always return an error but i see the query in my snowflake audit log, do you know if it is a limitation in that sense? 

**To Reproduce**
```elixir
Snowpack.query!(:snowpack, "delete from all_events_v3 where account_id='15094' and user_id='fake'")
[warning] Unable to execute query: No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
** (Snowpack.Error) No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
    (snowpack 0.7.4) lib/snowpack.ex:170: Snowpack.query!/4


Snowpack.query!(:snowpack, "delete from all_events_v3 where account_id='15094'", [], parse_results: false)
[warning] Unable to execute query: No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
** (Snowpack.Error) No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
    (snowpack 0.7.4) lib/snowpack.ex:170: Snowpack.query!/4


Snowpack.query!(:snowpack, "delete from all_events_v3 where account_id=?", ["15094"], parse_results: false)
[warning] Unable to execute query: No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
** (Snowpack.Error) No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
    (snowpack 0.7.4) lib/snowpack.ex:170: Snowpack.query!/4
```

i can't use prepare statements either

```elixir
iex(6)> query = Snowpack.prepare!(:snowpack, "delete_events", "delete from all_events_v3 where account_id=?")
%Snowpack.Query{
  columns: nil,
  name: "delete_events",
  num_params: nil,
  ref: nil,
  statement: "delete from all_events_v3 where account_id=?",
  type: nil
}
iex(7)> Snowpack.execute(:snowpack, query, ["15094"])
[warning] Unable to execute query: No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1167924348
{:error,
 %Snowpack.Error{
   message: "No SQL-driver information available. | ODBC_CODE \a | SNOWFLAKE_CODE 1167924348",
   native_code: "1167924348",
   odbc_code: "\a"
 }}
```

but for example this works

```
Snowpack.query!(:snowpack, "select current_user()")
%Snowpack.Result{columns: ["CURRENT_USER()"], num_rows: 1, rows: [["MYUSER"]]}
```

**Expected behavior**
it should not be returning an error but instead succeed 

**Additional context**
I'm testing this using the ARM version of snowflake and odbc

**Comment by forest** [comment]
I added a test for `DELETE` [here](https://github.com/HGInsights/snowpack/pull/42) and it is passing, so my guess is a configuration or permissions issue. That error message is not entirely helpful.

Can you run other select queries that hit your real Snowflake tables?

I also added some steps that we use to run on ARM to the readme.

**Comment by sescobb27** [comment]
hey @forest thanks for you fast response, is really weird, select works and i'm using a staging DB which i have permissions and we are also evaluating snowflex but they hay a similar issue with parametrized deletions, but in their case, it works when we use it this way, i'm going to try the steps you use in your readme for ARM and see if that changes something, thank you.

```elixir
# splited for readability 
Snowflex.sql_query(
	SnowflakeConnection, 
	"delete from all_events_v3 where account_id='15094'", 
	[ timeout: :timer.hours(1), map_nulls_to_nil?: true ]
)
```

**Comment by sescobb27** [comment]
I already replaced unixodbc with libiodbc did the same as in the PR you linked but still the same

```elixir
iex(1)> Snowpack.query!(:snowpack, "select current_user()")
%Snowpack.Result{columns: ["CURRENT_USER()"], num_rows: 1, rows: [["SIMON"]]}
iex(2)> Snowpack.query!(:snowpack, "select * from all_events_v3 where account_id = '15094'")
%Snowpack.Result{columns: ["ID", "ACCOUNT_ID", "USER_ID", "NAME", ...], num_rows: 0, rows: []}
iex(3)> Snowpack.query!(:snowpack, "delete from all_events_v3 where account_id = ?", ["15094"], parse_results: false)
[warning] Unable to execute query: No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1270928116
** (Snowpack.Error) No SQL-driver information available. | ODBC_CODE ^G | SNOWFLAKE_CODE 1270928116
    (snowpack 0.7.4) lib/snowpack.ex:170: Snowpack.query!/4
```

**Comment by forest** [comment]
Do you see the query in the Snowflake query logs? I'm wondering if the issue is before the query is made to SF or after when the results are handled.

**Comment by sescobb27** [comment]
yes, this is what i'm seeing in the query history

![Screen Shot 2022-07-20 at 10 11 09 AM](https://user-images.githubusercontent.com/1157892/180018089-b8fad2f3-57e2-4a50-a2ad-9aa099d4166d.png)

**Comment by forest** [comment]
I think I found the issue. Erlang ODBC incorrectly returns an error for DML (INSERT, UPDATE, DELETE) when there are no results returned. I need to confirm with a test and then make a fix.

**Comment by forest** [comment]
Did the row you delete with `account_id = '15094'` actually get deleted from SF?

**Comment by sescobb27** [comment]
hey forest, i'm not sure about this, for example when i exec that query in snowflex i get `{:updated, 0}` (no parametrized) but with snowpack i get an error, and no, it is not deleting data as i'm just testing it works before running it against a real account just to be safe, but it should be returning 0 rows still

**Comment by forest** [comment]
@sescobb27 let me know if this fix resolves your issue.

**Comment by sescobb27** [comment]
hey forest, well yeah, that indeed worked, i'm going to try with real data and going to see how it goes, thank you!!!!
